### ISSUE TITLE
Transpile to ES5

### ISSUE THREAD

**Issue by tehmaestro** [xorgy/grapheme-iterator#2]
Hi, thank you so much for taking the time to implement this. I'm trying do to a test run, so I want to transpile, bundle and just `<script>` tag the library. I haven't done this in ages. Would a webpack config like this work:
```
var path = require("path");
module.exports = {
	mode: "production",
	output: {
		path: path.join(__dirname, "dist"),
		filename: "bundle.js",
		library: "grapheme-iterator",
		libraryTarget: "amd"
	},
    module: {
        rules: [
          {
            test: /\.m?js$/,
            exclude: /(node_modules|bower_components)/,
            use: {
              loader: 'babel-loader',
              options: {
                presets: ['@babel/preset-env']
              }
            }
          }
        ]
    },
    target: ['web', 'es5']
};
```

**Comment by xorgy** [comment]
It should work, though note that it uses [typed arrays](https://caniuse.com/typedarrays) so not every ES5 browser ever released will support it unmodified.

**Comment by tehmaestro** [comment]
Thanks for the info.

Here's the result: https://gist.github.com/tehmaestro/37dc95dfb0565d8c618affde59a0ce43
If anyone wants to use it.
